### PR TITLE
Fix gallery-build with pillow >= 10.0.0

### LINKED ISSUE #127: Something went wrong while generating the thumbnails: module 'PIL.Image' has no attribute 'ANTIALIAS'
Hi, when i try to run `gallery-build` in WSL (after succesfully run 'gallery-init' i receive this output

Building the Simple Photo Gallery...
Generating thumbnails...
Something went wrong while generating the thumbnails: module 'PIL.Image' has no attribute 'ANTIALIAS'

and i not able to complete the creation of my gallery...

thanks for your help

ps: i installed this tool today so i'm with the latest version...

### PR DESCRIPTION
**Pull request by rohieb**
Fixes #127

PIL.Image.ANTIALIAS was [deprecated in pillow 9.1.0](https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants) and finally [removed in pillow 10.0.0](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants). Check if we can use the old API, if not, use the new API.

### CODE REVIEW

**Comment by haltakov** [comment]
Sorry, for my slow response. Just put the following on the main [README](https://github.com/haltakov/simple-photo-gallery#simple-photo-gallery). Let me know if you are interested.

> Important: I'm currently very busy in my job, so I don't have much time to support this project. It seems there is some interest in it on a regular basis, so I'd be happy to give admin access to another developer that wants to maintain/develop the project further. Please get in touch with me if you are interested.

**Review by haltakov — APPROVED** [review]
